name: CI/CD

on:
  push:
    branches: [ main,dev]
  pull_request:
    branches: [ main,dev]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint backend
        run: npm run lint || echo "No lint script"

      - name: TypeScript check backend
        run: npx tsc --noEmit || echo "No TypeScript in backend"

      - name: Run backend tests
        run: npm test || echo "No tests yet"

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run lint || echo "No lint script"

      - name: TypeScript check frontend
        run: npx tsc --noEmit

      - name: Build frontend
        run: npm run build

      - name: Run frontend tests
        run: npm test || echo "No tests yet"